name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d myapp_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - "4444:4444"
        options: >-
          --health-cmd="curl -f http://localhost:4444/wd/hub/status"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6
        bundler-cache: true
    
    - name: Install JavaScript packages
      run: yarn install

    - name: Cache Ruby gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
      
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        gem install bundler
        bundle install

    - name: Setup database
      run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails db:seed

    - name: Check MIME type of image
      run: file --mime-type spec/fixtures/images/noimage.png


    - name: Run RSpec
      run: bundle exec rspec

    - name: Run RuboCop
      run: bundle exec rubocop --fail-level W
